name: data_repository
description: The data repo of the project teachOnMars.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  dio: ^5.1.1

dev_dependencies:
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # generate: true
